version: '3'
services:
    pia-qbittorrent:
        image: j4ym0/pia-qbittorrent
        container_name: pia-qbittorrent
        cap_add:
            - NET_ADMIN
        environment:
            - REGION=Netherlands
            - USER=
            - PASSWORD=
        volumes:
            - ./config:/config
            - ./downloads:/downloads
        ports:
            - "8888:8888"
        restart: unless-stopped
